### ISSUE TITLE
pyATS IOSXE Error on Step36: Store Data

### ISSUE THREAD

**Issue by nouse4it** [automateyournetwork/magic_carpet#110]
**Describe the bug**
When I run the IOXSE pyATS Job with a valid testbedfile, via `pyats run job IOS_XE_magic_carpet_job.py --testbed-file testbed/testbed_ios_xe.yaml` the scripts starts to collect data but crashes on Step36, with the following error:
![error_iosxe](https://user-images.githubusercontent.com/73893641/117147574-ab539700-adb5-11eb-9d94-b47db1bff631.jpg)

```
2021-05-05T15:17:40: %AETEST-ERROR: Caught an exception while executing section parse:
2021-05-05T15:17:40: %AETEST-ERROR: Traceback (most recent call last):
2021-05-05T15:17:40: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/IOS_XE_magic_carpet.py", line 225, in parse
2021-05-05T15:17:40: %AETEST-ERROR:     parsed_output_type = learned_acl_template.render(to_parse_access_list=self.learned_acl['acls'],filetype_loop_jinja2=filetype)
2021-05-05T15:17:40: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
2021-05-05T15:17:40: %AETEST-ERROR:     self.environment.handle_exception()
2021-05-05T15:17:40: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
2021-05-05T15:17:40: %AETEST-ERROR:     reraise(*rewrite_traceback_stack(source=source))
2021-05-05T15:17:40: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
2021-05-05T15:17:40: %AETEST-ERROR:     raise value.with_traceback(tb)
2021-05-05T15:17:40: %AETEST-ERROR:   File "templates/cisco/ios_xe/learned_acl.j2", line 5, in top-level template code
2021-05-05T15:17:40: %AETEST-ERROR:     {{ list }},{{ ace }},{{ to_parse_access_list[list].aces[ace].actions.forwarding }},{{ to_parse_access_list[list].aces[ace].actions.logging | default ("No Logging") }},Source Protocol,N/A,N/A,UDP,{{ to_parse_access_list[list].aces[ace].matches.l4.udp.source_port.operator.operator }},{{ to_parse_access_list[list].aces[ace].matches.l4.udp.source_port.operator.port }}{% else %}{% if to_parse_access_list[list].aces[ace].matches.l4.udp.destination_port is defined%}
2021-05-05T15:17:40: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
2021-05-05T15:17:40: %AETEST-ERROR:     return getattr(obj, attribute)
2021-05-05T15:17:40: %AETEST-ERROR: jinja2.exceptions.UndefinedError: 'genie.ops.base.maker.CmdDict object' has no attribute 'operator'
```

**To Reproduce**
Run  `pyats run job IOS_XE_magic_carpet_job.py --testbed-file testbed/testbed_ios_xe.yaml` against a real Cisco 9300L Switch with Cisco IOSXE 16.12.4

**Expected behavior**
Collect all output and store them in the cave of wonders

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Python: Version 3.8.7

**Comment by automateyournetwork** [comment]
Thanks I see that maybe your ACL does not have an operator? it is crashing because of a missing value - let me patch in a test for operator in this template thanks - hold tight

**Comment by nouse4it** [comment]
That seems to didn´t fix the error. The Error Message stays the same. But I found an additional Messages above the Jinja Error:
```
/usr/lib/node_modules/markmap-cli/node_modules/update-notifier/index.js:58
                        } catch {
                                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/markmap-cli/bin/cli.js:3:24)

**Comment by automateyournetwork** [comment]
Could you maybe look at the JSON file for learned_acl and send me one
sections ? Your ACLs are missing operators or something. But I need the
json you can replace any IPs or sensitive data with dummy data

**Comment by nouse4it** [comment]
Sure, hope this is enough? If you need more, let me know:

```
{
    "acls": {
        "10": {
            "aces": {
                "10": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_ipv4_network": {
                                    "10.10.10.20 0.0.0.0": {
                                        "source_ipv4_network": "10.10.10.20 0.0.0.0"
                                    }
                                }
                            }
                        }
                    },
                    "name": "10",
                    "statistics": {
                        "matched_packets": "12165300"
                    }
                },
                "20": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_ipv4_network": {
                                    "10.10.10.21 0.0.0.0": {
                                        "source_ipv4_network": "10.10.10.21 0.0.0.0"
                                    }
                                }
                            }
                        }
                    },
                    "name": "20",
                    "statistics": {
                        "matched_packets": "1166428"
                    }
                },
                "30": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_ipv4_network": {
                                    "10.10.10.22 0.0.0.0": {
                                        "source_ipv4_network": "10.10.10.22 0.0.0.0"
                                    }
                                }
                            }
                        }
                    },
                    "name": "30"
                },
                "40": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_ipv4_network": {
                                    "10.10.10.23 0.0.0.0": {
                                        "source_ipv4_network": "10.10.10.23 0.0.0.0"
                                    }
                                }
                            }
                        }
                    },
                    "name": "40",
                    "statistics": {
                        "matched_packets": "34752882"
                    }
                }
            },
            "name": "10",
            "type": "ipv4-acl-type"
```

**Comment by automateyournetwork** [comment]
Thanks I will fix the templates accordingly thanks I will do this after
work

**Comment by automateyournetwork** [comment]
Hi !

This is the logic you should be hitting I think and I use "N/A" for the
operator and port - I dont know why it is looking for an Operator / Port
you should be hitting this first piece of logic

    "acls": {
        "10": {
            "aces": {
                "10": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_ipv4_network": {
                                    "10.10.10.20 0.0.0.0": {
                                        "source_ipv4_network":
"10.10.10.20 0.0.0.0"

I don't quite know what to do to fix this ?

What do you think?
Access Control List,
Access Control Entry,
Permission,
Logging,
Source Network,
Destination Network,
L3 Protocol,
L4 Protocol,
Operator,
Port
  {% for list in to_parse_access_list %}
    {% if to_parse_access_list[list].aces is defined %}
      {% for ace in to_parse_access_list[list].aces %}
        {% if to_parse_access_list[list].aces[ace].matches.l3 is defined %}
          {% if to_parse_access_list[list].aces[ace].matches.l3.ipv4 is
defined %}
            {% if to_parse_access_list[list].aces[ace].matches.l3.ipv4.
source_network is defined %}
              {% for source_network in to_parse_access_list[list].aces[ace].
matches.l3.ipv4.source_network %}
{{ list }},
{{ ace }},
{{ to_parse_access_list[list].aces[ace].actions.forwarding }},
{{ to_parse_access_list[list].aces[ace].actions.logging | default (
"No Logging") }},
{{ to_parse_access_list[list].aces[ace].matches.l3.ipv4.source_network[
source_network] | replace("{'source_network': ","") | replace("}","") |
replace("'","") }},
{{ to_parse_access_list[list].aces[ace].matches.l3.ipv4.destination_network
 | replace(" {'destination_network':","") | replace("}","") | replace("{",""
) | replace("'","") | replace(":","") | default("N/A") }},
{{ to_parse_access_list[list].aces[ace].matches.l3.ipv4.protocol | default(
"N/A") }},
N/A,
N/A,
N/A

**Comment by nouse4it** [comment]
It looks like it crashed when it wanted to parse our qos policy, which sometime only has protocols and ports but no IP´s in it. 
Looks like this
```
ip access-list extended qos_policy
remark REMARK
permit udp any eq 9999 any
permit udp any any eq 9999
permit tcp any any eq 9999
permit tcp any eq 9999 any
permit udp any any eq 9998
permit udp any eq 9998any
permit tcp any eq 9998any
permit tcp any any eq 9998
```

But the funny thing, is no after i pulled the project again, now it parses the acls, of course sometimes with N/A.
But it parses it without failing and stopping the whole script.

**Comment by automateyournetwork** [comment]
Thanks

If you send me the RAW JSON of the Above policy I will try to handle this
use case logic as well

So you think it works ok now for you / it runs to completion??? What do you
think of the output? How many devices are you doing?

Thanks

John

**Comment by nouse4it** [comment]
Hi John, 
you can find the raw policy in json at the end.

Unfortunately, when I run the script as told my over dm (uncomment lines and empty j2 template), the script skips over the acl part, but still gets some other issues. I´m running it against one switch at the moment.
I receive the following error several times on step 35:
```
/usr/lib/node_modules/markmap-cli/node_modules/update-notifier/index.js:58
                        } catch {
                                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/markmap-cli/bin/cli.js:3:24)
/usr/lib/node_modules/markmap-cli/node_modules/update-notifier/index.js:58
                        } catch {
                                ^
```

The scripts goes through the next steps, after this error and then reports the follwoing error on Step 41, where the scripts then crashes (aborts):
```
2021-05-12T10:27:28: %AETEST-ERROR: Caught an exception while executing section parse:
2021-05-12T10:27:28: %AETEST-ERROR: Traceback (most recent call last):
2021-05-12T10:27:28: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/IOS_XE_magic_carpet.py", line 843, in parse
2021-05-12T10:27:28: %AETEST-ERROR:     parsed_output_type = sh_access_sessions_interface_details_template.render(to_parse_access_interface_details=self.parsed_show_ip_access_session_interface_details['interfaces'],filetype_loop_jinja2=filetype)
2021-05-12T10:27:28: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
2021-05-12T10:27:28: %AETEST-ERROR:     self.environment.handle_exception()
2021-05-12T10:27:28: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
2021-05-12T10:27:28: %AETEST-ERROR:     reraise(*rewrite_traceback_stack(source=source))
2021-05-12T10:27:28: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
2021-05-12T10:27:28: %AETEST-ERROR:     raise value.with_traceback(tb)
2021-05-12T10:27:28: %AETEST-ERROR:   File "templates/cisco/ios_xe/show_access_sessions_interface_details.j2", line 2, in top-level template code
2021-05-12T10:27:28: %AETEST-ERROR:     {{ interface }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].user_name }},{{ mac_address }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].current_policy }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].domain }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].ipv4_address }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].ipv6_address }},{% if to_parse_access_interface_details[interface].mac_address[mac_address].local_policies is defined %}{{ to_parse_access_interface_details[interface].mac_address[mac_address].local_policies.vlan_group.vlan }}{% else %}"N/A"{% endif %},{{ method }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].method_status[method].state }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].oper_host_mode }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].session_timeout.remaining }},{{ to_parse_access_interface_details[interface].mac_address[mac_address].status }}{% endfor %}{% endfor %}{% endfor %}{% else %}{% if filetype_loop_jinja2 == "md" %}
2021-05-12T10:27:28: %AETEST-ERROR:   File "/home/user/scripts/magic_carpet/venv_magic_carpet/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
2021-05-12T10:27:28: %AETEST-ERROR:     return getattr(obj, attribute)
2021-05-12T10:27:28: %AETEST-ERROR: jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'vlan_group'
```
seems like the script can handle when the port has an assinged vlan by server policy.





```
{"qos_policy": {
    "aces": {
        "10": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "udp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "udp": {
                        "source_port": {
                            "operator": {
                                "operator": "eq",
                                "port": "9999"
                            }
                        }
                    }
                }
            },
            "name": "10"
        },
        "20": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "udp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "udp": {
                        "destination_port": {
                            "operator": {
                                "operator": "eq",
                                "port": 9999
                            }
                        }
                    }
                }
            },
            "name": "20"
        },
        "30": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "tcp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "tcp": {
                        "destination_port": {
                            "operator": {
                                "operator": "eq",
                                "port": 9999
                            }
                        },
                        "established": false
                    }
                }
            },
            "name": "30"
        },
        "40": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "tcp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "tcp": {
                        "established": false,
                        "source_port": {
                            "operator": {
                                "operator": "eq",
                                "port": "9999"
                            }
                        }
                    }
                }
            },
            "name": "40"
        },
        "50": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "udp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "udp": {
                        "destination_port": {
                            "operator": {
                                "operator": "eq",
                                "port": 9998
                            }
                        }
                    }
                }
            },
            "name": "50"
        },
        "60": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "udp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "udp": {
                        "source_port": {
                            "operator": {
                                "operator": "eq",
                                "port": "9998"
                            }
                        }
                    }
                }
            },
            "name": "60"
        },
        "70": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "tcp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "tcp": {
                        "established": false,
                        "source_port": {
                            "operator": {
                                "operator": "eq",
                                "port": "9998"
                            }
                        }
                    }
                }
            },
            "name": "70"
        },
        "80": {
            "actions": {
                "forwarding": "permit",
                "logging": "log-none"
            },
            "matches": {
                "l3": {
                    "ipv4": {
                        "destination_ipv4_network": {
                            "any": {
                                "destination_ipv4_network": "any"
                            }
                        },
                        "protocol": "tcp",
                        "source_ipv4_network": {
                            "any": {
                                "source_ipv4_network": "any"
                            }
                        }
                    }
                },
                "l4": {
                    "tcp": {
                        "destination_port": {
                            "operator": {
                                "operator": "eq",
                                "port": 9998
                            }
                        },
                        "established": false
                    }
                }
            },
            "name": "80"
        }
    },
    "name": "qos_policy",
    "type": "ipv4-acl-type"
    }
}
```

**Comment by automateyournetwork** [comment]
Ok couple of things are happening

anything with node / js / markmap is your node.js - make sure this is
installed cleanly or comment out every reference to the markmap CLI

also it looks like your new error

jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'vlan_group'


is related to template show_ip_access_session_interface_details.j2


You can remove all this template for now and send me the JSON from
this command I need like the ACL one try to find what is missing
vlan_group


thanks for your patience I will work on your qos fix asap
